_Xnet_"		"Nova Zelândia (Xnet)"
	"CDNLoc_MX_to_US"		"México aos Estados Unidos"
	"CDNLoc_Mexico"		"México"
	"CDNLoc_Argentina"		"Argentina"
	"CDNLoc_Chile"		"Chile"
	"CDNLoc_Peru"		"Peru"
	"CDNLoc_Colombia"		"Colômbia"
	"CDNLoc_Australia___WA__WAIX_"		"Austrália - Ocidental (WAIX)"
	"CDNLoc_Australia___VIC__VIC_IX_"		"Austrália - VIC (VIC-IX)"
	"CDNLoc_Australia___QLD__QLD_IX_"		"Austrália - QLD (QLD-IX)"
	"CDNLoc_Europe_to_Middle_East"		"Europa ao Médio Oriente"
	"CDNLoc_Turkey"		"Turquia"
	"CDNLoc_Egypt"		"Egipto"
	"CDNLoc_Saudi_Arabia"		"Arábia Saudita"
	"CDNLoc_United_Arab_Emirates"		"Emirados Árabes Unidos"
	"CDNLoc_Pakistan"		"Paquistão"
	"CDNLoc_Luxembourg"		"Luxemburgo"
	"CDNLoc_West_Africa"		"África Oeste"
	"CDNLoc_East_Africa"		"África Este"
	"CDNLoc_Northwest_Africa"		"África Noroeste"
	"CDNLoc_Canada___Edmonton"		"Canadá - Edmonton"
	"CDNLoc_Canada___Calgary"		"Canadá - Calgary"
	"CDNLoc_Canada___Winnipeg"		"Canadá - Winnipeg"
	"CDNLoc_Canada___Ottawa"		"Canadá - Ottawa"
	"CDNLoc_China__Perfect_World_Unicom_"		"China (Perfect World Unicom)"
	"CDNLoc_China__Perfect_World_Telecom_"		"China (Perfect World Telecom)"
	"CDNLoc_Central_America"		"América Central"
	"CDNLoc_Caribbean"		"Caraíbas"
	"CDNLoc_India___Chennai"		"Índia - Chennai"
	"CDNLoc_India___Delhi"		"Índia - Deli"
	"CDNLoc_India___Bangalore"		"Índia - Bangalore"
	"CDNLoc_India___Hyderabad"		"Índia - Hyderabad"
	"CDNLoc_India___Kolkata"		"Índia - Calcutá"
	"CDNLoc_US___Honolulu"		"EUA - Honolulu"
	"CDNLoc_US___Anchorage"		"EUA - Anchorage"
	"CDNLoc_China___Guangzhou"		"China - Cantão"
	"CDNLoc_Russia___St._Petersburg"		"Rússia - São Petersburgo"
	"CDNLoc_Russia___Rostov_na_Donu"		"Rússia - Rostov-na-Donu"
	"CDNLoc_Russia___Kazan"		"Rússia - Kazan"
	"CDNLoc_Russia___Vladivostok"		"Rússia - Vladivostoque"
	"CDNLoc_Brazil___Recife"	"Brasil - Recife"
	"CDNLoc_Brazil___Brasilia"	"Brasil - Brasília"
	"CDNLoc_Brazil___Rio_de_Janeiro"	"Brasil - Rio de Janeiro"
	"CDNLoc_Brazil___Porto_Alegre"	"Brasil - Porto Alegre"
	"CDNLoc_Russia___Irkutsk"		"Rússia - Irkutsk"
	"CDNLoc_Kazakhstan"	"Cazaquistão"
	"CDNLoc_China___Wuhan"	"China - Wuhan"
	"CDNLoc_China___Xi'an"	"China - Xian"
	"CDNLoc_Mongolia"	"Mongólia"
	"CDNLoc_Venezuela"	"Venezuela"
	"CDNLoc_Ecuador"	"Equador"
	"CDNLoc_Bolivia"	"Bolívia"
	"CDNLoc_Belarus"	"Bielorrússia"
	"CDNLoc_Brazil___Sao_Paulo"	"Brasil - São Paulo"	                                      
	"CDNLoc_Bulgaria"			"Bulgária"
	"CDNLoc_Caucasus"			"Cáucaso"
	"CDNLoc_Central_Asia"		"Ásia Central"
	"CDNLoc_China___Changsha"	"China - Changsha"
	"CDNLoc_China___Harbin"		"China - Harbin"
	"CDNLoc_China___Kunming"	"China - Kunming"
	"CDNLoc_China___Qingdao"	"China - Qingdao"
	"CDNLoc_China___Urumqi"		"China - Urumqi"
	"CDNLoc_China___Zhengzhou"	"China - Zhengzhou"
	"CDNLoc_Croatia"			"Croácia"
	"CDNLoc_Iceland,_Greenland,_and_Faroe_Islands"	"Islândia, Gronelândia e Ilhas Faroé"
	"CDNLoc_Italy___Milan"		"Itália - Milão"
	"CDNLoc_Italy___Rome"		"Itália - Roma"
	"CDNLoc_Japan___Fukuoka"	"Japão - Fukuoka"
	"CDNLoc_Japan___Nagoya"		"Japão - Nagoya"
	"CDNLoc_Japan___Osaka"		"Japão - Osaka"
	"CDNLoc_Japan___Sapporo"	"Japão - Sapporo"
	"CDNLoc_Japan___Sendai"		"Japão - Sendai"
	"CDNLoc_Japan___Tokyo"		"Japão - Tóquio"
	"CDNLoc_Pacific_Islands"	"Ilhas do Pacífico"
	"CDNLoc_Poland___Katowice"	"Polónia - Katowice"
	"CDNLoc_Poland___Warsaw"	"Polónia - Varsóvia"
	"CDNLoc_Portugal"			"Portugal"
	"CDNLoc_South_Korea___Busan"	"Coreia do Sul - Busan"
	"CDNLoc_South_Korea___Seoul"	"Coreia do Sul - Seul"
	"CDNLoc_Spain___Barcelona"	"Espanh