	"ControllerBinding_HapticIntensityDpad_Low_Description" "Usar uma resposta háptica de intensidade baixa."
	"ControllerBinding_HapticIntensityDpad_Medium" "Intensidade háptica - Média"
	"ControllerBinding_HapticIntensityDpad_Medium_Description" "Usar uma resposta háptica de intensidade média."
	"ControllerBinding_HapticIntensityDpad_High" "Intensidade háptica - Alta"
	"ControllerBinding_HapticIntensityDpad_High_Description" "Usar uma resposta háptica de intensidade alta."
	"ControllerBinding_HapticIntensityDpad_ActivatorPref" "Intensidade háptica - Usar definições do ativador"
	"ControllerBinding_HapticIntensityDpad_ActivatorPref_Description" "A resposta háptica será controlada pelas definições de cada ativador."
	"ControllerBinding_HapticIntensityDpadGA" "Intensidade háptica manual"
	"ControllerBinding_HapticIntensityDpadGA_Description" "Isto define a intensidade da resposta háptica. É enviada uma resposta háptica quando um input é ativado ou desativado."
	"ControllerBinding_HapticIntensityDpadGA_Off" "Intensidade háptica - Off"
	"ControllerBinding_HapticIntensityDpadGA_Off_Description" "Não usar resposta háptica neste modo."
	"ControllerBinding_HapticIntensityDpadGA_Low" "Intensidade háptica - Baixa"
	"ControllerBinding_HapticIntensityDpadGA_Low_Description" "Usar uma resposta háptica de intensidade baixa."
	"ControllerBinding_HapticIntensityDpadGA_Medium" "Intensidade háptica - Média"
	"ControllerBinding_HapticIntensityDpadGA_Medium_Description" "Usar uma resposta háptica de intensidade média."
	"ControllerBinding_HapticIntensityDpadGA_High" "Intensidade háptica - Alta"
	"ControllerBinding_HapticIntensityDpadGA_High_Description" "Usar uma resposta háptica de intensidade alta."
	"ControllerBinding_HapticIntensityDpadGA_ActivatorPref" "Intensidade háptica - Usar definições do ativador"
	"ControllerBinding_HapticIntensityDpadGA_ActivatorPref_Description" "A resposta háptica será controlada pelas definições de cada ativador."
	"ControllerBinding_Deadzone" "Zona morta"
	"ControllerBinding_Deadzone_Description" "Ações do pad direcional não serão desempenhadas se 