ia, Gronelândia e Ilhas Faroé"
	"CDNLoc_Israel"		"Israel"
	"CDNLoc_US___Seattle"		"EUA - Seattle"
	"CDNLoc_Japan"		"Japão"
	"CDNLoc_China___Hong_Kong"		"China - Hong Kong"
	"CDNLoc_Thailand"		"Tailândia"
	"CDNLoc_Singapore"		"Singapura"
	"CDNLoc_India___Mumbai"		"Índia - Mumbai"
	"CDNLoc_Italy"		"Itália"
	"CDNLoc_Poland"		"Polónia"
	"CDNLoc_Russia___Yekaterinburg"		"Rússia - Yekaterinburgo"
	"CDNLoc_Spain___Portugal"		"Portugal e Espanha"
	"CDNLoc_Denmark"		"Dinamarca"
	"CDNLoc_Czech_Republic"		"República Checa"
	"CDNLoc_Greece"		"Grécia"
	"CDNLoc_Indonesia"		"Indonésia"
	"CDNLoc_Philippines"		"Filipinas"
	"CDNLoc_China___Beijing"		"China - Pequim"
	"CDNLoc_China___Shanghai"		"China - Xangai"
	"CDNLoc_China___Chengdu"		"China - Chengdu"
	"CDNLoc_US___Denver"		"EUA - Denver"
	"CDNLoc_US___Atlanta"		"EUA - Atlanta"
	"CDNLoc_Australia___QLD"		"Austrália - QLD"
	"CDNLoc_Australia___NSW"		"Austrália - NSW"
	"CDNLoc_Australia___VIC"		"Austrália - VIC"
	"CDNLoc_Australia___SA"		"Austrália - Sul"
	"CDNLoc_Australia___WA"		"Austrália - Ocidental"
	"CDNLoc_Australia___NSW__3FL_"		"Austrália - NSW (3FL)"
	"CDNLoc_Australia___VIC__Gamespace_"		"Austrália - VIC (Gamespace)"
	"CDNLoc_Australia___SA__Adam_Internet_"		"Austrália - Sul (Adam Internet)"
	"CDNLoc_Australia___SA__Internode_"		"Austrália - SA (Internode)"
	"CDNLoc_Australia___WA__3FL_"		"Austrália - Ocidental (3FL)"
	"CDNLoc_Australia___WA__EGN_"		"Austrália - Ocidental (EGN)"
	"CDNLoc_Russia___Novosibirsk"		"Rússia - Novosibirsk"
	"CDNLoc_US___Washington,_DC"		"EUA - Washington, DC"
	"CDNLoc_US___Los_Angeles"		"EUA - Los Angeles"
	"CDNLoc_US___Dallas"		"EUA - Dallas"
	"CDNLoc_Sweden"		"Suécia"
	"CDNLoc_Norway"		"Noruega"
	"CDNLoc_Finland"		"Finlândia"
	"CDNLoc_Ireland"		"Irlanda"
	"CDNLoc_Cambodia"		"Camboja"
	"CDNLoc_Vietnam"		"Vietname"
	"CDNLoc_Malaysia"		"Malásia"
	"CDNLoc_Ukraine"		"Ucrânia"
	"CDNLoc_US___San_Diego"		"EUA - San Diego"
	"CDNLoc_US___Sacramento"		"EUA - Sacramento"
	"CDNLoc_US___Minneapolis"		"EUA - Minneapolis"
	"CDNLoc_US___St._Louis"		"EUA - St. Louis"
	"CDNLoc_US___Houston"		"EUA - Houston"
	"CDNLoc_US___Detroit"		"EUA - Detroit"
	"CDNLoc_US___Pittsburgh"		"EUA - Pittsburgh"
	"CDNLoc_Canada___Montreal"		"Canadá - Montreal"
	"CDNLoc_US___Boston"		"EUA - Boston"
	"CDNLoc_US___Philadelphia"		"EUA - Filadélfia"
	"CDNLoc_US___Charlotte"		"EUA - Charlotte"
	"CDNLoc_UK___Manchester"		"Reino Unido - Manchester"
	"CDNLoc_Belgium"		"Bélgica"
	"CDNLoc_Germany___Dusseldorf"		"Alemanha - Dusseldórfia"
	"CDNLoc_Switzerland"		"Suíça"
	"CDNLoc_Germany_