own_LeftTriggerThreshold" "Mudança de modo - Gatilho esquerdo"
	"ControllerBinding_ModeShiftDropDown_LeftTriggerThreshold_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_RightTriggerThreshold" "Mudança de modo - Gatilho direito"
	"ControllerBinding_ModeShiftDropDown_RightTriggerThreshold_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_LeftBumper" "Mudança de modo - Botão superior esquerdo"
	"ControllerBinding_ModeShiftDropDown_LeftBumper_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_RightBumper" "Mudança de modo - Botão superior direito"
	"ControllerBinding_ModeShiftDropDown_RightBumper_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_LeftGrip" "Mudança de modo - Botão traseiro esquerdo"
	"ControllerBinding_ModeShiftDropDown_LeftGrip_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_RightGrip" "Mudança de modo - Botão traseiro direito"
	"ControllerBinding_ModeShiftDropDown_RightGrip_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_LeftPadClick" "Mudança de modo - Clique do pad esquerdo"
	"ControllerBinding_ModeShiftDropDown_LeftPadClick_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_RightPadClick" "Mudança de modo - Clique do pad direito"
	"ControllerBinding_ModeShiftDropDown_RightPadClick_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_LeftJoystickClick" "Mudança de modo - Clique do joystick"
	"ControllerBinding_ModeShiftDropDown_LeftJoystickClick_Description" "Quando pressionado, este botão irá mudar o modo normal do comando para o seu modo alternativo, que é definido neste ecrã."
	"ControllerBinding_ModeShiftDropDown_A" "Mudança de modo - Botão A"
	"ControllerBinding_ModeShiftDropDown_A_Description" "Quando pressionado, este botão irá mudar o modo normal d