Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao rodar no sentido dos ponteiros do relógio (sentido horário)."
	"ControllerBinding_ScrollWheelCounterClockwise" "Designação sentido anti-horário"
	"ControllerBinding_ScrollWheelCounterClockwise_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao rodar no sentido contrário ao dos ponteiros do relógio (sentido anti-horário)."
	"ControllerBinding_ScrollWheelClick" "Ação ao clicar"
	"ControllerBinding_ScrollWheelClick_Description" "Esta ação será desempenhada ao clicares com o pad/stick."
	"ControllerBinding_ScrollWheelList0" "Designação do item 1 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList0_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao primeiro ponto da roda."
	"ControllerBinding_ScrollWheelList1" "Designação do item 2 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList1_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao segundo ponto da roda."
	"ControllerBinding_ScrollWheelList2" "Designação do item 3 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList2_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao terceiro ponto da roda."
	"ControllerBinding_ScrollWheelList3" "Designação do item 4 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList3_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao quarto ponto da roda."
	"ControllerBinding_ScrollWheelList4" "Designação do item 5 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList4_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao quinto ponto da roda."
	"ControllerBinding_ScrollWheelList5" "Designação do item 6 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList5_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao sexto ponto da roda."
	"ControllerBinding_ScrollWheelList6" "Designação do item 7 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList6_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao sétimo ponto da roda."
	"ControllerBinding_ScrollWheelList7" "Designação do item 8 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList7_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao oitavo ponto da roda."
	"ControllerBinding_ScrollWheelList8" "Designação do item 9 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList8_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao nono ponto da roda."
	"ControllerBinding_ScrollWheelList9" "Designação do item 10 da roda de deslocamento"
	"ControllerBinding_ScrollWheelList9_Description" "Podes designar um botão ou tecla para ser interpretado pelo jogo ao chegar ao décimo ponto da roda."
	"ControllerBinding_ScrollWheelListWrap" "Repetir infinitamente"
	"ControllerBinding_ScrollWheelListWrap_Description" "Com esta opção ativa, a lista de itens voltará ao ponto inicial qu