ption"	"Off: A seleção no menu de ações não voltará ao início quando se chega ao fim."

	//MouseRegion
	"ControllerBinding_ModeDropDown_MouseRegion" "Tipo de input - Região do rato"
	"ControllerBinding_ModeDropDown_MouseRegion_Description" "Este input irá comportar-se como uma Região do Rato. A Região do Rato envia ações do rato para um jogo, mas trata o pad como um mapa à escala 1:1 relativamente ao espaço no ecrã. Desta forma, tocar num certo lugar do pad irá colocar o rato no mesmo lugar no ecrã. Além de funcionar muito bem com jogos vistos de cima, podes restringir as regiões a certas áreas do ecrã, podes alterar a sua escala, esticá-las e usá-las em combinação com a mudança de modo para selecionar mini-mapas, barras de ferramentas, o inventário, etc."
	"ControllerBinding_MouseRegionClick" "Ação ao clicar"
	"ControllerBinding_MouseRegionClick_Description" "Esta ação será desempenhada ao clicares com o pad/stick."
	"ControllerBinding_ScaleMouseRegion" "Tamanho da região"
	"ControllerBinding_ScaleMouseRegion_Description" "Isto irá definir o tamanho da região atribuída às bordas exteriores do pad/stick."
	"ControllerBinding_PositionXMouse" "Posição horizontal da região"
	"ControllerBinding_PositionXMouse_Description" "Isto é a posição horizontal no ecrã onde a região se irá centrar."
	"ControllerBinding_PositionYMouse" "Posição vertical da região"
	"ControllerBinding_PositionYMouse_Description" "Isto é a posição vertical no ecrã onde a região se irá centrar."
	"ControllerBinding_TeleportStart" "Mover rato ao ativar modo"
	"ControllerBinding_TeleportStart_On" "Mover rato ao ativar modo"
	"ControllerBinding_TeleportStart_Off" "Mover rato ao ativar modo"
	"ControllerBinding_TeleportStart_Description" "Ao ativar o modo, deve o rato ser movido para o centro da região?"
	"ControllerBinding_TeleportStart_On_Description"	"Mover o rato para o centro da região ao ativar o modo"
	"ControllerBinding_TeleportStart_Off_Description"	"Permanecer na posição atual do rato"
	"ControllerBinding_TeleportStop" "Repor posição do rato ao parar/no fim da mudança de modo"
	"ControllerBinding_TeleportStop_Description" "Quando paras de tocar ou ao desativar a mudança de modo, deve o rato ser movido de volta para a posição onde estava antes da ativação da mudança de modo?"
	"ControllerBinding_TeleportStop_On" "Mover cursor para a posição anterior"
	"ControllerBinding_TeleportStop_On_Description" "Isto irá mover o cursor para a posição anterior quando se deixa de tocar no touchpad ou no fim da mudança de modo."
	"ControllerBinding_TeleportStop_Off" "Manter cursor na posição atual"
	"ControllerBinding_TeleportStop_Off_Description" "Isto irá manter o cursor na posição atual assim que se deixar de tocar no touchpad ou no fim da mudança de modo."
	"ControllerBinding_HorizontalSensitivityMouseRegion" "Escala horizontal"
	"ControllerBinding_HorizontalSensitivityMouseRegion_Description" "Define a região horizontal. Podes usar isto para alterar a região no ecrã, por defeito circular, para uma elipse ou uma linha."
	"ControllerBinding_VerticalSensitivi