 ajusta o output da curva de resposta do joystick."
	"ControllerBinding_CurveExponent_joystick_mouse_Description" "Isto determina o mapeamento do input analógico de acordo com o output. Por predefinição, um mapeamento linear 1:1 é usado. Esta curva pode ser alterada para aumentar ou reduzir o rigor dos controlos."
	"ControllerBinding_CurveExponent_joystick_mouse_Linear" "Curva de resposta - Linear"
	"ControllerBinding_CurveExponent_joystick_mouse_Linear_Description" "Uma curva de resposta linear mapeia o input diretamente ao output numa proporção de 1:1. A 50% de distância, 50% de output será interpretado."
	"ControllerBinding_CurveExponent_joystick_mouse_1" "Curva de resposta - Agressiva"
	"ControllerBinding_CurveExponent_joystick_mouse_1_Description" "Uma curva de resposta agressiva chega a 100% mais rapidamente. O intervalo de baixo alcance é reduzido e o alcance máximo de output é alcançado mais rapidamente, proporcionando uma resposta mais rápida."
	"ControllerBinding_CurveExponent_joystick_mouse_2" "Curva de resposta - Relaxada"
	"ControllerBinding_CurveExponent_joystick_mouse_2_Description" "Uma curva de resposta relaxada chega a 100% mais lentamente. O intervalo de baixo alcance é maior, com o qual é possível usar controlos mais precisos, e o alcance máximo fica mais próximo nas bordas."
	"ControllerBinding_CurveExponent_joystick_mouse_3" "Curva de resposta - Ampla"
	"ControllerBinding_CurveExponent_joystick_mouse_3_Description" "Uma curva de resposta ampla chega aos 100% muito mais lentamente do que a predefinição. Há uma vasta gama de valores baixos que aumentam rapidamente nas bordas exteriores. Isto permite uma grande quantidade de valores baixos próximos do centro interior, subindo gradualmente para o valor máximo no exterior."
	"ControllerBinding_CurveExponent_joystick_mouse_4" "Curva de resposta - Extra ampla"
	"ControllerBinding_CurveExponent_joystick_mouse_4_Description" "Uma curva de resposta extra ampla proporciona uma vasta gama de valores baixos ao longo de uma faixa ampla, apenas alcançando 100% nos extremos."
	"ControllerBinding_CurveExponent_joystick_mouse_Custom" "Curva de resposta - Curva personalizada"
	"ControllerBinding_CurveExponent_joystick_mouse_Custom_Description" "Ajusta a curva de resposta para definires uma curva per