\"pressionar regular\" irão permanecer premidos enquanto este conjunto ou layer estiver ativo."
	"SettingsController_BindingTitle" "{s:bindingtitle}"
	"SettingsController_BindingTitle_ForController" "({s:controllername})"
	"SettingsController_BindingTitle_Guest" "Convidado"
	"SettingsController_BindingCreator" "Por {s:bindingcreator}"
	"SettingsController_Binding_Preview" "A pré-visualizar configuração"
	"SettingsController_AutosaveName"	"Configuração do comando"
	"SettingsController_AutosaveDescription"	"A tua configuração modificada para este jogo."
	"SettingsController_ModifiedBy"	"Modificado por ti, com base na configuração de {s:bindingcreator}."
	"SettingsController_ModifiedByOfficial" "Modificado por ti, com base na configuração oficial do jogo."
	"SettingsController_SwapToUnifiedPad"	"Usar pad unificado"
	"SettingsController_SwapToSplitPad"	"Usar pad dividido"
	"SettingsController_GenericJoystickSetupText"	"Se ativaste o configurador de comandos genéricos, poderás reconfigurar o comando em cada jogo através do mesmo configurador usado para Comandos Steam."
	"SettingsController_PS4SetupText"	"Se ativaste o Configurador de comando da PlayStation, poderás reconfigurar o comando em cada jogo através do mesmo configurador usado para Comandos Steam. \n\nAtenção: Quando ligado por Bluetooth, o comando deve ser desligado e ligado após a desativação do configurador. Desativar o configurador para um jogo específico também não funcionará."
	"SettingsController_XBoxSetupText"	"Se ativaste o Configurador de Xbox, poderás reconfigurar o comando em cada jogo através do mesmo configurador usado para Comandos Steam. \n\nAtenção: No Windows, poderás ter de ajustar as definições do Gravador de Jogo da Xbox para que o Botão Guide seja reconhecido."
	"SettingsController_XBoxDriverText"	"Se a opção \"Funcionalidades avançadas da Xbox\" estiver ativada, o Steam vai usar um driver personalizado para providenciar acesso a até 16 comandos da Xbox e permitir que configures as patilhas intercambiáveis de comandos Xbox Elite.\n\nAtenção: Tens de reiniciar o computador depois de instalares ou desinstalares o driver personalizado."
	"SettingsController_SwitchSetupText"	"Se ativaste o Configurador da Switch, pode