ng_HapticIntensity_joystick_move_Off_Description" "Não usar resposta háptica neste modo."
	"ControllerBinding_HapticIntensity_joystick_move_Low" "Intensidade háptica - Baixa"
	"ControllerBinding_HapticIntensity_joystick_move_Low_Description" "Usar uma resposta háptica de intensidade baixa."
	"ControllerBinding_HapticIntensity_joystick_move_Medium" "Intensidade háptica - Média"
	"ControllerBinding_HapticIntensity_joystick_move_Medium_Description" "Usar uma resposta háptica de intensidade média."
	"ControllerBinding_HapticIntensity_joystick_move_High" "Intensidade háptica - Alta"
	"ControllerBinding_HapticIntensity_joystick_move_High_Description" "Usar uma resposta háptica de intensidade alta."
	"ControllerBinding_GyroButton_joystick_move" "Botão do giroscópio"
	"ControllerBinding_GyroButton_joystick_move_Description" "O input do giroscópio pode ser ativado apenas com o pressionar de um botão."
	"ControllerBinding_GyroButton_joystick_move_GyroNone" "Botão do giroscópio - Sempre ativo"
	"ControllerBinding_GyroButton_joystick_move_GyroNone_Description" "O input do giroscópio estará sempre ativo."
	"ControllerBinding_GyroButton_joystick_move_GyroTouchRight" "Botão do giroscópio - Toque no pad direito"
	"ControllerBinding_GyroButton_joystick_move_GyroTouchRight_Description" "O input do giroscópio só será interpretado quando se tocar no touchpad direito."
	"ControllerBinding_GyroButton_joystick_move_GyroTouchLeft" "Botão do giroscópio - Toque no pad esquerdo"
	"ControllerBinding_GyroButton_joystick_move_GyroTouchLeft_Description" "O input do giroscópio só será interpretado quando se tocar no touchpad esquerdo."
	"ControllerBinding_GyroButton_joystick_move_GyroTouchCenter" "Botão do giroscópio - Toque no pad unificado"
	"ControllerBinding_GyroButton_joystick_move_GyroTouchCenter_Description" "O input do giroscópio será interpretado quando se tocar em qualquer parte do touchpad."
	"ControllerBinding_GyroButton_joystick_move_GyroClickRight" "Botão do giroscópio - Clique do pad direito"
	"ControllerBinding_GyroButton_joystick_move_GyroClickRight_Description" "O input do giroscópio só será interpretado quando